<#
.SYNOPSIS
    Builds a per-user license matrix (one True/False column per licensed product) and
    returns it to the pipeline — displayed in the console by default, or piped to
    Export-Csv / Export-Excel / Out-GridView / whatever you want.

.DESCRIPTION
    Fixes the "System.Object[]" problem you get from a naive AssignedLicenses export by
    building one explicit column per unique product license found in the tenant, keyed
    on the friendly display name (not the raw GUID or internal SkuPartNumber code name
    like "SPE_F1"). Designed for spotting redundant/overlapping licensing — e.g. a user
    who holds both Microsoft 365 F3 and a standalone Exchange Online Plan 1, or both
    Microsoft 365 Business Premium and a standalone Defender for Office 365 Plan 1.

    This script has no export logic of its own — it just emits clean PSCustomObjects.
    Run it bare and PowerShell's default formatter displays a table in the console.
    Pipe it anywhere else and the objects flow through normally.

.PARAMETER IncludeDisabledUsers
    Include disabled (blocked sign-in) accounts. Off by default — most licensing/overlap
    audits only care about active users.

.PARAMETER MappingCsvPath
    Optional path to a locally cached copy of Microsoft's "Product names and service
    plan identifiers for licensing" CSV. If omitted, the script downloads the current
    version and saves a copy to %TEMP% — pass that path back in on a later run to skip
    the download entirely.

.NOTES
    Requires: Microsoft.Graph.Users, Microsoft.Graph.Identity.DirectoryManagement
    Scopes:   User.Read.All, Organization.Read.All (delegated or application — both
              read-only, consistent with a least-privilege audit identity)

    If you're already connected to Graph, this script reuses that session
    automatically — it will not reconnect or prompt. To run this standalone with
    certificate auth instead of interactive login, replace the Connect-MgGraph line in
    section 1 with your usual -ClientId/-TenantId/-CertificateThumbprint pattern.

    With DisplayName + UPN + AccountEnabled + LicenseCount + one column per product,
    a wide tenant can easily produce 15-20+ columns. A bare console table will get
    truncated to fit your terminal width. For actually spotting overlap, Out-GridView
    (see examples below) is usually more useful than the plain table — it's built
    exactly for "wide object, want to filter/sort visually."

    ----------------------------------------------------------------------------------
    ### Disclaimer: ###

    This script was generated by Claude AI on September 18th 2026 using Sonnet 5 on
    Claude Desktop client using a written prompt request by Marco Janse.
    ----------------------------------------------------------------------------------

    Version: 1.0
    Last modified on: 2026-09-18
    By Claude AI and Marco Janse

    Version history:

    1.0 - Initial generated version by Claude Sonnet 5 and modified by Marco Janse

.EXAMPLE
    .\Export-M365LicenseMatrix.ps1
    Displays the matrix in the console using PowerShell's default table formatting.

.EXAMPLE
    .\Export-M365LicenseMatrix.ps1 | Out-GridView -Title "License Matrix"
    Interactive, sortable/filterable grid — the best option for eyeballing overlap
    without leaving the console. (Windows PowerShell: built in. PowerShell 7: install
    the Microsoft.PowerShell.GraphicalTools module first.)

.EXAMPLE
    .\Export-M365LicenseMatrix.ps1 | Export-Csv -Path .\Licenses.csv -NoTypeInformation -Encoding UTF8

.EXAMPLE
    .\Export-M365LicenseMatrix.ps1 | Export-Excel -Path .\Licenses.xlsx -AutoSize -TableName Licenses -WorksheetName "License Matrix"
    Requires the ImportExcel module (Install-Module ImportExcel) — the script checks
    for it at startup and lets you know if it's missing.

.EXAMPLE
    .\Export-M365LicenseMatrix.ps1 | Where-Object { $_.'Microsoft 365 F3' -and $_.'Exchange Online (Plan 1)' } | Format-Table DisplayName, UserPrincipalName
    Filter first, then display only the columns you care about — the most useful
    pattern for a specific overlap check like the F3/EXO P1 one we were looking at.
#>

[CmdletBinding()]
param(
    [switch]$IncludeDisabledUsers,
    [string]$MappingCsvPath
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# 1. Connect (reuse an existing session if there is one —
#    otherwise prompt for delegated login)
# ---------------------------------------------------------------------------
if (-not (Get-MgContext)) {
    Write-Host "No existing Graph session found — connecting interactively." -ForegroundColor Cyan
    Connect-MgGraph -Scopes "User.Read.All", "Organization.Read.All" -NoWelcome
}
else {
    Write-Host "Reusing existing Graph session ($((Get-MgContext).Account))." -ForegroundColor Cyan
}

# Courtesy heads-up about Export-Excel — purely informational, doesn't block anything.
if (Get-Module -ListAvailable -Name ImportExcel) {
    Write-Host "ImportExcel module detected — you can pipe the output to Export-Excel." -ForegroundColor DarkGray
}
else {
    Write-Host "Tip: 'Install-Module ImportExcel' if you want to pipe the output straight to a formatted .xlsx via Export-Excel." -ForegroundColor DarkGray
}

# ---------------------------------------------------------------------------
# 2. Get the SKUs actually present in this tenant
# ---------------------------------------------------------------------------
Write-Host "Retrieving subscribed SKUs..." -ForegroundColor Cyan
$tenantSkus = Get-MgSubscribedSku -All

# ---------------------------------------------------------------------------
# 3. Resolve SKU GUIDs -> friendly product names, via Microsoft's official
#    mapping file. Falls back to a well-known community-maintained mirror if
#    Microsoft's own download link doesn't respond — its URL embeds a
#    rotating document ID and periodically moves.
# ---------------------------------------------------------------------------
if ($MappingCsvPath -and (Test-Path $MappingCsvPath)) {
    Write-Host "Using cached mapping file: $MappingCsvPath" -ForegroundColor Cyan
    $mapping = Import-Csv $MappingCsvPath
}
else {
    Write-Host "Downloading the current product name mapping from Microsoft..." -ForegroundColor Cyan
    $tempMapping = Join-Path $env:TEMP "M365-License-Mapping.csv"
    $officialUrl = "https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv"
    $fallbackUrl = "https://raw.githubusercontent.com/merill/license/main/license.csv"
    $ProgressPreference = 'SilentlyContinue'
    try {
        Invoke-WebRequest -Uri $officialUrl -OutFile $tempMapping -UseBasicParsing
    }
    catch {
        Write-Warning "Microsoft's official download link didn't respond — falling back to the community-maintained mirror (merill/license)."
        Invoke-WebRequest -Uri $fallbackUrl -OutFile $tempMapping -UseBasicParsing
    }
    $mapping = Import-Csv $tempMapping
    Write-Host "Saved a copy to $tempMapping — pass it via -MappingCsvPath next time to skip the download." -ForegroundColor DarkGray
}

# The mapping file has one row per SERVICE PLAN, so the same product GUID repeats many
# times — de-duplicate down to one friendly name per SKU GUID.
$skuNameLookup = @{}
foreach ($row in ($mapping | Sort-Object GUID -Unique)) {
    if ($row.GUID -and -not $skuNameLookup.ContainsKey($row.GUID)) {
        $skuNameLookup[$row.GUID] = $row.Product_Display_Name
    }
}

# Resolve the friendly name for every SKU actually in this tenant. Fall back to the
# internal SkuPartNumber (e.g. "SPE_F1") if a brand-new SKU isn't in the mapping yet —
# this happens for SKUs Microsoft has shipped very recently.
$skuFriendlyNames = @{}
foreach ($sku in $tenantSkus) {
    $friendly = $skuNameLookup[$sku.SkuId]
    if (-not $friendly) {
        Write-Warning "No friendly name found for SkuId $($sku.SkuId) (SkuPartNumber: $($sku.SkuPartNumber)) — using the part number instead."
        $friendly = $sku.SkuPartNumber
    }
    $skuFriendlyNames[$sku.SkuId] = $friendly
}

$uniqueLicenseNames = $skuFriendlyNames.Values | Sort-Object -Unique
Write-Host "Found $($uniqueLicenseNames.Count) unique licensed products in this tenant." -ForegroundColor Cyan

# Precompute a reverse lookup (friendly name -> the SkuId(s) that map to it) once,
# rather than re-deriving it for every single user in the loop below.
$nameToSkuIds = @{}
foreach ($kvp in $skuFriendlyNames.GetEnumerator()) {
    if (-not $nameToSkuIds.ContainsKey($kvp.Value)) { $nameToSkuIds[$kvp.Value] = @() }
    $nameToSkuIds[$kvp.Value] += $kvp.Key
}

# ---------------------------------------------------------------------------
# 4. Pull every user's assigned licenses and build one True/False column per
#    unique product. This is what avoids "System.Object[]" — that text is
#    just PowerShell's default .ToString() on the raw AssignedLicenses array;
#    building explicit named columns sidesteps it entirely.
# ---------------------------------------------------------------------------
Write-Host "Retrieving users (this can take a while on larger tenants)..." -ForegroundColor Cyan
$users = Get-MgUser -All -Property "Id,DisplayName,UserPrincipalName,AccountEnabled,AssignedLicenses"

if (-not $IncludeDisabledUsers) {
    $users = $users | Where-Object { $_.AccountEnabled }
}

$total = @($users).Count
$i = 0
$results = foreach ($user in $users) {
    $i++
    Write-Progress -Activity "Building license matrix" -Status "$i of $total" -PercentComplete (($i / $total) * 100)

    $assignedSkuIds = @($user.AssignedLicenses).SkuId

    $row = [ordered]@{
        DisplayName       = $user.DisplayName
        UserPrincipalName = $user.UserPrincipalName
        AccountEnabled    = $user.AccountEnabled
        LicenseCount      = @($user.AssignedLicenses).Count
    }

    foreach ($licenseName in $uniqueLicenseNames) {
        $row[$licenseName] = [bool]($assignedSkuIds | Where-Object { $_ -in $nameToSkuIds[$licenseName] })
    }

    [PSCustomObject]$row
}
Write-Progress -Activity "Building license matrix" -Completed

Write-Host "Done. Returning $($results.Count) user records to the pipeline.`n" -ForegroundColor Green

# ---------------------------------------------------------------------------
# 5. Emit to the pipeline. Run bare -> PowerShell's default table view.
#    Piped -> flows straight into Export-Csv / Export-Excel / Out-GridView /
#    Where-Object / whatever comes next.
# ---------------------------------------------------------------------------
$results